<% host_app_module = @scope_module |> String.split(".") |> List.first() %>
defmodule <%= host_app_module %>.Lockspire.SmokeE2ETest do
  @moduledoc """
  Default-profile OAuth/OIDC smoke generated by `mix lockspire.install`.

  It exercises discovery, JWKS, and authorization-code routing with PKCE S256
  using the host endpoint. The host's normal Lockspire configuration remains in
  effect; this test does not enable a stronger security profile or weaken any
  default.
  """
  use ExUnit.Case, async: false

  @endpoint <%= @web_module %>.Endpoint

  import Phoenix.ConnTest
  import Plug.Conn

  test "discovery and JWKS are published" do
    discovery =
      build_conn()
      |> put_req_header("accept", "application/json")
      |> get("<%= @mount_path %>/.well-known/openid-configuration")

    assert discovery.status == 200
    assert %{"jwks_uri" => jwks_uri} = Jason.decode!(discovery.resp_body)

    jwks =
      build_conn()
      |> put_req_header("accept", "application/json")
      |> get(URI.parse(jwks_uri).path)

    assert jwks.status == 200
    assert %{"keys" => keys} = Jason.decode!(jwks.resp_body)
    assert is_list(keys)
  end

  test "authorization-code requests require S256 and exact redirect matching" do
    client = register_client!()

    valid_request = authorize_params(client)

    s256_response =
      build_conn()
      |> get("<%= @mount_path %>/authorize", valid_request)

    assert s256_response.status in [302, 303]

    invalid_redirect =
      build_conn()
      |> get("<%= @mount_path %>/authorize", Map.put(valid_request, "redirect_uri", client.redirect_uri <> "/"))

    assert invalid_redirect.status == 400
    assert invalid_redirect.resp_body =~ "redirect_uri must match a registered URI"

    plain_pkce =
      build_conn()
      |> get("<%= @mount_path %>/authorize", Map.put(valid_request, "code_challenge_method", "plain"))

    assert plain_pkce.status in [302, 303]
    assert redirected_to(plain_pkce) =~ "error=invalid_request"
  end

  defp register_client! do
    unique = System.unique_integer([:positive])
    redirect_uri = "https://client.example.com/callback/#{unique}"

    assert {:ok, registration} =
             Lockspire.Clients.register_client(%{
               client_id: "lockspire-smoke-#{unique}",
               client_type: :public,
               redirect_uris: [redirect_uri],
               allowed_scopes: ["profile"],
               allowed_grant_types: ["authorization_code"],
               allowed_response_types: ["code"],
               token_endpoint_auth_method: :none,
               name: "Lockspire Smoke #{unique}"
             })

    %{client_id: registration.client.client_id, redirect_uri: redirect_uri}
  end

  defp authorize_params(client) do
    verifier = "lockspire-smoke-#{System.unique_integer([:positive])}"

    %{
      "client_id" => client.client_id,
      "response_type" => "code",
      "redirect_uri" => client.redirect_uri,
      "scope" => "openid profile",
      "nonce" => "nonce-#{System.unique_integer([:positive])}",
      "state" => "state-#{System.unique_integer([:positive])}",
      "code_challenge" => code_challenge(verifier),
      "code_challenge_method" => "S256"
    }
  end

  defp code_challenge(verifier) do
    :sha256
    |> :crypto.hash(verifier)
    |> Base.url_encode64(padding: false)
  end
end
