<% host_app_module = @scope_module |> String.split(".") |> List.first() %>
defmodule <%= host_app_module %>.Lockspire.FapiSmokeE2ETest do
  @moduledoc """
  FAPI 2.0 smoke E2E generated by `mix lockspire.install`.

  This test exercises Lockspire's FAPI 2.0 enforcement through the host-owned
  HTTP seam and Lockspire's public API surface only.

  Template baseline note: this file is generated from the library install task,
  where `@app_module` was `<%= @app_module %>` at render time.

  Expectation for the PAR-required smoke:
  - Configure `security_profile: :fapi_2_0_security` in the host before running
    this file if you want the direct `/authorize` rejection to assert the FAPI
    2.0 PAR mandate.
  """
  use ExUnit.Case, async: false

  @moduletag :integration
  @endpoint Lockspire.Web.Router

  import Phoenix.ConnTest
  import Plug.Conn

  setup do
    %{client: register_client!()}
  end

  test "FAPI 2.0 rejects direct authorize requests without PAR and emits iss", %{client: client} do
    conn =
      build_conn(:get, "/authorize", authorize_params(client))
      |> @endpoint.call(@endpoint.init([]))

    assert conn.status in [302, 303]

    params =
      conn
      |> location()
      |> query_params()

    assert params["error"] == "invalid_request"

    assert params["error_description"] == "request_uri from the PAR endpoint is required",
           """
           Expected the host to enforce the FAPI 2.0 PAR requirement.
           Set `security_profile: :fapi_2_0_security` in the host Lockspire config before running this smoke.
           """

    assert params["iss"] == Lockspire.issuer()
  end

  test "authorize rejects trailing-slash redirect_uri drift with exact matching", %{client: client} do
    conn =
      build_conn(:get, "/authorize", authorize_params(client, %{
        "redirect_uri" => client.redirect_uri <> "/"
      }))
      |> @endpoint.call(@endpoint.init([]))

    assert conn.status == 400
    assert conn.resp_body =~ "redirect_uri must match a registered URI"
  end

  test "authorize rejects extra-query redirect_uri drift with exact matching", %{client: client} do
    conn =
      build_conn(:get, "/authorize", authorize_params(client, %{
        "redirect_uri" => client.redirect_uri <> "?extra=1"
      }))
      |> @endpoint.call(@endpoint.init([]))

    assert conn.status == 400
    assert conn.resp_body =~ "redirect_uri must match a registered URI"
  end

  test "authorization error redirects always include iss", %{client: client} do
    conn =
      build_conn(:get, "/authorize", authorize_params(client, %{
        "response_type" => "token"
      }))
      |> @endpoint.call(@endpoint.init([]))

    assert conn.status in [302, 303]

    params =
      conn
      |> location()
      |> query_params()

    assert params["error"]
    assert params["iss"] == Lockspire.issuer()
  end

  defp register_client! do
    unique = System.unique_integer([:positive])
    redirect_uri = "https://client.example.com/callback/#{unique}"

    assert {:ok, registration} =
             Lockspire.Clients.register_client(%{
               client_id: "lockspire-fapi-smoke-#{unique}",
               client_type: :public,
               redirect_uris: [redirect_uri],
               allowed_scopes: ["openid"],
               allowed_grant_types: ["authorization_code"],
               allowed_response_types: ["code"],
               token_endpoint_auth_method: :none,
               name: "Lockspire FAPI Smoke #{unique}"
             })

    %{client_id: registration.client.client_id, redirect_uri: redirect_uri}
  end

  defp authorize_params(client, overrides \\ %{}) do
    Map.merge(
      %{
        "client_id" => client.client_id,
        "response_type" => "code",
        "redirect_uri" => client.redirect_uri,
        "scope" => "openid",
        "nonce" => "lockspire-fapi-smoke-nonce",
        "state" => "lockspire-fapi-smoke-state",
        "code_challenge" => code_challenge("lockspire-fapi-smoke-verifier"),
        "code_challenge_method" => "S256"
      },
      overrides
    )
  end

  defp location(conn) do
    conn
    |> get_resp_header("location")
    |> List.first()
    |> Kernel.||(
      flunk("Expected redirect location from /authorize, got status=#{conn.status} body=#{inspect(conn.resp_body)}")
    )
  end

  defp query_params(location) do
    location
    |> URI.parse()
    |> Map.get(:query, "")
    |> URI.decode_query()
  end

  defp code_challenge(verifier) do
    :sha256
    |> :crypto.hash(verifier)
    |> Base.url_encode64(padding: false)
  end
end
